export const vehicles = [
    {
        id: 1,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 2,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 3,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 4,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 5,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 6,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 7,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 8,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 9,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 10,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 25,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 11,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 12,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 23,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 13,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 14,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 15,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 16,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 17,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 18,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 19,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
    {
        id: 20,
        make: "Audi",
        model: "A4",
        manufactured: 2014,
        engine_abrv: "2.0d",
        img_url: "https://images.dealer.com/ddc/vehicles/2020/Audi/A4/Sedan/perspective/front-left/2020_24.png",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium ducimus blanditiis et iusto",
        price: "12000,00 €"
    },
    {
        id: 21,
        make: "Aston Martin",
        model: "DB5 James Bond Edition",
        manufactured: 1963,
        engine_abrv: "4.0l",
        img_url: "https://static.wikia.nocookie.net/forzamotorsport/images/1/12/HOR_XB1_JBE_AM_DB5.png/revision/latest?cb=20191125215511",
        odo: "80,000 km",
        desc: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium",
        price: "12000,00 €"
    },
    {
        id: 22,
        make: "Hyundai",
        model: "Elantra",
        manufactured: 2011,
        engine_abrv: "1.6l",
        img_url: "https://upload.wikimedia.org/wikipedia/commons/f/fe/2011_Hyundai_Elantra_GLS_--_06-02-2011_1.jpg",
        odo: "80,000 km",
        desc: "At vero eos.",
        price: "12000,00 €"
    },
]