# Generated by Django 3.1.6 on 2021-03-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20210323_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles.make'),
            preserve_default=False,
        ),
    ]
