# Generated by Django 3.1.6 on 2021-03-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_model_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.make'),
        ),
    ]
