# Generated by Django 3.1.6 on 2021-03-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20210324_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.make'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.model'),
            preserve_default=False,
        ),
    ]
