# Generated by Django 3.1.6 on 2021-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20210324_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='abrv',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
